/* tslint:disable */
/* eslint-disable */
/**
 *
 * The  API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface DeviceTable
 */
export interface DeviceTable {
  /**
   * Unique identifier of the device.
   *
   * @type {string}
   * @memberof DeviceTable
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  d_id: string;

  /**
   * Indicates whether the device is currently active.
   *
   * @type {boolean}
   * @memberof DeviceTable
   * @example true
   */
  active: boolean;

  /**
   * Serial number of the device.
   *
   * @type {string}
   * @memberof DeviceTable
   * @example SN123456789
   */
  serial: string;

  /**
   * Version of the device structure, indicating hardware or software configurations.
   *
   * @type {string}
   * @memberof DeviceTable
   * @example v1.0.0
   */
  structure_version: string;

  /**
   * Model of the device, indicating the device`s hardware or software configuration.
   *
   * @type {string}
   * @memberof DeviceTable
   */
  model: string;

  /**
   * Password for the device, used for configurations or access.
   *
   * @type {string}
   * @memberof DeviceTable
   * @example P@ssw0rd!
   */
  password: string;
}
