/* tslint:disable */
/* eslint-disable */
/**
 *
 * The  API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface DevicesOfOrganization
 */
export interface DevicesOfOrganization {
  /**
   * Identificador único del dispositivo
   *
   * @type {string}
   * @memberof DevicesOfOrganization
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  id: string;

  /**
   * Tipo de dispositivo
   *
   * @type {string}
   * @memberof DevicesOfOrganization
   * @example sensor
   */
  type: string;

  /**
   * Número de serie del dispositivo
   *
   * @type {string}
   * @memberof DevicesOfOrganization
   * @example SN-001
   */
  serial: string;
}
