/* tslint:disable */
/* eslint-disable */
/**
 * 
 * The  API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface EmailsDTO
 */
export interface EmailsDTO {
  /**
   * First email of the legal guardian of the patient.
   *
   * @type {string}
   * @memberof EmailsDTO
   * @example email@test.com
   */
  email1: string;

  /**
   * Second email of the legal guardian of the patient.
   *
   * @type {string}
   * @memberof EmailsDTO
   * @example email@test.com
   */
  email2?: string;
}
