/* tslint:disable */
/* eslint-disable */
/**
 *
 * The  API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Menu } from './menu';
/**
 *
 *
 * @export
 * @interface GetMenuInfo
 */
export interface GetMenuInfo {
  /**
   * List of menu items
   *
   * @type {Array<Menu>}
   * @memberof GetMenuInfo
   */
  menu: Array<Menu>;

  /**
   * Indicates whether the menu is active
   *
   * @type {boolean}
   * @memberof GetMenuInfo
   * @example true
   */
  is_active: boolean;

  /**
   * Indicates whether the user has premium status
   *
   * @type {boolean}
   * @memberof GetMenuInfo
   * @example false
   */
  premium: boolean;
}
