/* tslint:disable */
/* eslint-disable */
/**
 * Marsinet
 * The marsinet API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface LoginResponseDto
 */
export interface LoginResponseDto {
  /**
   * @type {string}
   * @memberof LoginResponseDto
   */
  access_token: string;

  /**
   * @type {string}
   * @memberof LoginResponseDto
   */
  refresh_token: string;
}
