/* tslint:disable */
/* eslint-disable */
/**
 * Marsinet
 * The marsinet API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface Menu
 */
export interface Menu {
  /**
   * CSS class name for the menu icon
   *
   * @type {string}
   * @memberof Menu
   */
  i_class_name: string;

  /**
   * Router link path for navigation
   *
   * @type {string}
   * @memberof Menu
   */
  to: string;

  /**
   * Translation key for the menu label
   *
   * @type {string}
   * @memberof Menu
   */
  translation: string;
}
