/* tslint:disable */
/* eslint-disable */
/**
 * 
 * The  API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface OrganizationUpdateDto
 */
export interface OrganizationUpdateDto {
  /**
   * Name of the organization
   *
   * @type {string}
   * @memberof OrganizationUpdateDto
   */
  name: string;

  /**
   * Street name of the organization address
   *
   * @type {string}
   * @memberof OrganizationUpdateDto
   */
  street_name: string;

  /**
   * Street number of the organization address
   *
   * @type {string}
   * @memberof OrganizationUpdateDto
   */
  street_number: string;

  /**
   * Postal code of the organization
   *
   * @type {string}
   * @memberof OrganizationUpdateDto
   */
  postal_code: string;

  /**
   * Country where the organization is located
   *
   * @type {string}
   * @memberof OrganizationUpdateDto
   */
  country: string;

  /**
   * State or region where the organization is located
   *
   * @type {string}
   * @memberof OrganizationUpdateDto
   */
  state: string;

  /**
   * City where the organization is located
   *
   * @type {string}
   * @memberof OrganizationUpdateDto
   */
  city: string;
}
