/* tslint:disable */
/* eslint-disable */
/**
 *
 * The  API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface RemovePatientOrgDTO
 */
export interface RemovePatientOrgDTO {
  /**
   * Id of the patient
   *
   * @type {string}
   * @memberof RemovePatientOrgDTO
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  p_id: string;

  /**
   * Id of the organization
   *
   * @type {string}
   * @memberof RemovePatientOrgDTO
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  o_id: string;
}
