/* tslint:disable */
/* eslint-disable */
/**
 * Marsinet
 * The marsinet API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface ResetPasswordResponseDto
 */
export interface ResetPasswordResponseDto {
  /**
   * @type {boolean}
   * @memberof ResetPasswordResponseDto
   */
  success: boolean;
}
