/* tslint:disable */
/* eslint-disable */
/**
 *
 * The  API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface UpdateOrganizationDto
 */
export interface UpdateOrganizationDto {
  /**
   * The name of the organization
   *
   * @type {string}
   * @memberof UpdateOrganizationDto
   * @example Doe Enterprises
   */
  name?: string;

  /**
   * The city where the organization is located
   *
   * @type {string}
   * @memberof UpdateOrganizationDto
   * @example New York
   */
  city?: string;

  /**
   * The country where the organization is located
   *
   * @type {string}
   * @memberof UpdateOrganizationDto
   * @example USA
   */
  country?: string;

  /**
   * The postal code of the organization's address
   *
   * @type {string}
   * @memberof UpdateOrganizationDto
   * @example 10001
   */
  postal_code?: string;

  /**
   * The street name of the organization's address
   *
   * @type {string}
   * @memberof UpdateOrganizationDto
   * @example 5th Avenue
   */
  street_name?: string;

  /**
   * The street number of the organization's address
   *
   * @type {string}
   * @memberof UpdateOrganizationDto
   * @example 789
   */
  street_number?: string;

  /**
   * The state or region where the organization is located
   *
   * @type {string}
   * @memberof UpdateOrganizationDto
   * @example NY
   */
  state?: string;
}
