/* tslint:disable */
/* eslint-disable */
/**
 * 
 * The  API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface UpdateActiveDeviceDto
 */
export interface UpdateActiveDeviceDto {
  /**
   * Indicates the new active status of the device
   *
   * @type {boolean}
   * @memberof UpdateActiveDeviceDto
   * @example true
   */
  active: boolean;
}
