/* tslint:disable */
/* eslint-disable */
/**
 * 
 * The  API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UserTable } from './user-table';
/**
 *
 *
 * @export
 * @interface UsersView
 */
export interface UsersView {
  /**
   * Flag indicating if the user can create organizations
   *
   * @type {boolean}
   * @memberof UsersView
   * @example true
   */
  can_create_organization: boolean;

  /**
   * List of user details
   *
   * @type {Array<UserTable>}
   * @memberof UsersView
   */
  users: Array<UserTable>;
}
