/* tslint:disable */
/* eslint-disable */
/**
 * 
 * The  API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface UserTable
 */
export interface UserTable {
  /**
   * The UUID of the user
   *
   * @type {string}
   * @memberof UserTable
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  u_id: string;

  /**
   * The first name of the user
   *
   * @type {string}
   * @memberof UserTable
   * @example John
   */
  name: string;

  /**
   * The surname or last name of the user
   *
   * @type {string}
   * @memberof UserTable
   * @example Doe
   */
  surnames: string;

  /**
   * The email address of the user
   *
   * @type {string}
   * @memberof UserTable
   * @example john.doe@example.com
   */
  email: string;

  /**
   * The UUID of the organization associated with the user
   *
   * @type {string}
   * @memberof UserTable
   * @example 456e4577-e89b-12d3-a456-426655440000
   */
  o_id: string;

  /**
   * Indicates if the user is an administrator
   *
   * @type {boolean}
   * @memberof UserTable
   * @example true
   */
  is_admin: boolean;

  /**
   * The role of the user within the system
   *
   * @type {string}
   * @memberof UserTable
   * @example manager
   */
  role: string;

  /**
   * Indicates if the user account is active
   *
   * @type {boolean}
   * @memberof UserTable
   * @example true
   */
  active: boolean;
}
