/* tslint:disable */
/* eslint-disable */
/**
 *
 * The  API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface UserUpdateDto
 */
export interface UserUpdateDto {
  /**
   * User's first name
   *
   * @type {string}
   * @memberof UserUpdateDto
   */
  name: string;

  /**
   * User's last name
   *
   * @type {string}
   * @memberof UserUpdateDto
   */
  surnames: string;

  /**
   * User's date of birth
   *
   * @type {any}
   * @memberof UserUpdateDto
   * @example 1990-01-01
   */
  birth_date: any;

  /**
   * User's nationality
   *
   * @type {string}
   * @memberof UserUpdateDto
   */
  nationality: string;

  /**
   * User's phone number
   *
   * @type {string}
   * @memberof UserUpdateDto
   * @example +1234567890
   */
  phone: string;
}
