version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Asumiendo que tu archivo package.json está en el directorio raíz
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "luxon"
      - dependency-name: "uuid"
      - dependency-name: "archiver"
      - dependency-name: "pidusage"
      - dependency-name: "dotenv"
