/* tslint:disable */
/* eslint-disable */
/**
 * 
 * The  API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/admin-api';
export * from './apis/alarm-api';
export * from './apis/devices-api';
export * from './apis/ingestion-api';
export * from './apis/my-account-api';
export * from './apis/patients-api';
export * from './apis/sessions-api';
export * from './apis/user-not-authenticated-api';
export * from './apis/users-api';
