/* tslint:disable */
/* eslint-disable */
/**
 * Marsinet
 * The marsinet API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { User } from './user';
/**
 *
 *
 * @export
 * @interface MyAccount
 */
export interface MyAccount {
  /**
   * User's profile
   *
   * @type {User}
   * @memberof MyAccount
   */
  user: User;

  /**
   * User's organization details
   *
   * @type {any}
   * @memberof MyAccount
   */
  organization: any;

  /**
   * Indicates if the user can edit their profile
   *
   * @type {boolean}
   * @memberof MyAccount
   * @example true
   */
  can_edit: boolean;
}
