/* tslint:disable */
/* eslint-disable */
/**
 * Marsinet
 * The marsinet API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface MyDevices
 */
export interface MyDevices {
  /**
   * Device ID
   *
   * @type {string}
   * @memberof MyDevices
   * @example 123e4567-e89b-12d3-a456-426614174000
   */
  id: string;

  /**
   * Device model
   *
   * @type {string}
   * @memberof MyDevices
   * @example Model X
   */
  model: string;

  /**
   * Device serial number
   *
   * @type {string}
   * @memberof MyDevices
   * @example SN123456789
   */
  serial: string;

  /**
   * Indicates if the device is active
   *
   * @type {boolean}
   * @memberof MyDevices
   * @example true
   */
  active: boolean;
}
