/* tslint:disable */
/* eslint-disable */
/**
 * Marsinet
 * The marsinet API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
  /**
   * @type {string}
   * @memberof RegisterDto
   */
  email: string;

  /**
   * @type {string}
   * @memberof RegisterDto
   */
  password: string;

  /**
   * @type {string}
   * @memberof RegisterDto
   */
  name: string;

  /**
   * @type {string}
   * @memberof RegisterDto
   */
  surnames: string;

  /**
   * @type {string}
   * @memberof RegisterDto
   */
  phone: string;

  /**
   * @type {any}
   * @memberof RegisterDto
   */
  birth_date: any;

  /**
   * @type {string}
   * @memberof RegisterDto
   */
  nationality: string;

  /**
   * @type {string}
   * @memberof RegisterDto
   */
  organization_id: string;
}
