/* tslint:disable */
/* eslint-disable */
/**
 * Marsinet
 * The marsinet API description
 *
 * OpenAPI spec version: 2.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UserData } from './user-data';
/**
 *
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   * User's email address
   *
   * @type {string}
   * @memberof User
   * @example user@example.com
   */
  email: string;

  /**
   * Detailed user data
   *
   * @type {UserData}
   * @memberof User
   */
  user_data: UserData;
}
